### ISSUE TITLE
[Front]_View GET 요청 

### ISSUE THREAD

**Issue by sud665** [sud665/YMJ-pre-task#12]
### ISSUE
- Group:  `Client`
- Type:  `feature`
- Detail:  작성된 페이지 컨슈머 페이지에 리다이렉트 기능 추가 

### TODO
1. [ ] 서버에 GET 요청 
2. [ ] 작성된 페이지 구성으로 리다이랙트 
3. [ ] endpoint /consumer GET 요청 보내기 

### Estimated time
> Pick one
