### ISSUE TITLE
[Front]_폴더_트리_생성

### ISSUE THREAD

**Issue by sud665** [sud665/YMJ-pre-task#2]
### ISSUE
- Group:  `Client`
- Type: `feature`
- Detail: 클라이언트 부분 폴더 구조 생성 

### TODO
1. [ ] 2개의 Pages 가 필요 (어드민, 컨슈머) 
2. [ ] 각 기능별 컴포넌트 생성 
3. [ ] 함수 사용하는 유틸리트 폴더 생성
